### PR TITLE
update to node 16,  FIX HASHER BUG

### LINKED ISSUE #62: Upgrade to Node 16 minimum with xxhash-wasm v1.0+
xxhash-wasm has a 3-4x improvement, but requires a minimum of Node 15+.

We are finally ready to drop Node 14 now that Node 20 is out.

https://github.com/jungomi/xxhash-wasm/blob/main/CHANGELOG.md

### LINKED ISSUE #85: Xxhasher not returning hex-encoded string values
Xxhasher was not returning hex-encoded string values, instead returns base 10.

### Steps to reproduce
XxHasher.hash64("15") returns "17181926294437511708"

### Expected behaviour
XxHasher.hash64("15") returns "ee7276ee58e4421c"

### PR DESCRIPTION
**Pull request by shannonwells**
Problem
=======
We need to update to Node16+ as 15.* is @ end-of-life. Closes #62, Fixes #85

Solution
========
Update to nodejs 16.15.1, update some packages and fix anything broken.

**Important:** This revealed a bug in the Xxhasher code that was not converting to hex-encoded strings as the [bloom filter expects](https://github.com/LibertyDSNP/parquetjs/blob/2c733b5c7a647b9a8ebe9a13d300f41537ef60e2/lib/bloom/sbbf.ts#L357)

Steps to Verify:
----------------
Tests should pass

### CODE REVIEW

File: lib/bloom/xxhasher.ts [hunk 1]
```diff
@@ -17,7 +17,7 @@ export default class XxHasher {
     private static h64 = xxhash().then(x => x.h64)
 
     private async hashit(value: string): Promise<string> {
-        return (await XxHasher.h64)(value)
+        return (await XxHasher.h64)(value).toString(16)
```
Comment (shannonwells) [inline lib/bloom/xxhasher.ts:20]: the bloom filter code expects Hex-encoded strings.

File: lib/util.ts [hunk 2]
```diff
@@ -174,7 +174,7 @@ export const osend = function(os: WriteStreamMinimal) {
   });
 }
 
-export const osopen = function(path: string | Buffer | URL, opts?: string | WriterOptions): Promise<WriteStream> {
+export const osopen = function(path: string | Buffer | URL, opts?: WriterOptions): Promise<WriteStream> {
```
Comment (shannonwells) [inline lib/util.ts:177]: removed `string` as a type because the only thing that calls osopen can never pass a string.

**Review by wilwade — APPROVED** [review]
Nice!
